import type { MockExamQuestion } from "./types"

export const fullMockQuestionBank: MockExamQuestion[] = [
  // --- Section 1: Business Analysis Foundations (6 Qs) ---
  {
    id: "q-mock-01",
    domain: "Foundations",
    moduleNumber: "01",
    prompt: "What is the primary objective of a Business Analyst in an organizational change initiative?",
    explanation: "The BA role is to understand business situations, identify root causes, and define requirements for holistic business solutions.",
    syllabusReference: "BCS BA Foundation Section 1.1: What is Business Analysis",
    options: [
      { key: "a", text: "To write programming code and configure databases", isCorrect: false },
      { key: "b", text: "To investigate business situations and identify options for improvement", isCorrect: true },
      { key: "c", text: "To manage daily developer schedules and project budgets", isCorrect: false },
      { key: "d", text: "To replace senior management in approving commercial investments", isCorrect: false },
    ],
  },
  {
    id: "q-mock-02",
    domain: "Foundations",
    moduleNumber: "01",
    prompt: "Which competency category includes empathy, relationship building, and political awareness?",
    explanation: "Behavioral competencies focus on interpersonal skills, communication, influence, and emotional intelligence.",
    syllabusReference: "BCS BA Foundation Section 1.2: Competencies of a BA",
    options: [
      { key: "a", text: "Behavioral skills and personal qualities", isCorrect: true },
      { key: "b", text: "Technical system engineering", isCorrect: false },
      { key: "c", text: "Financial accounting standards", isCorrect: false },
      { key: "d", text: "Software architectural design", isCorrect: false },
    ],
  },
  {
    id: "q-mock-03",
    domain: "Foundations",
    moduleNumber: "01",
    prompt: "In the Business Analysis Service Framework (BASF), which service focuses on assessing strategic alignment?",
    explanation: "Strategy implementation / Business situation analysis evaluates alignment between organizational goals and proposed initiatives.",
    syllabusReference: "BCS BA Foundation Section 1.3: Business Analysis Service Framework",
    options: [
      { key: "a", text: "User acceptance test execution", isCorrect: false },
      { key: "b", text: "Strategy implementation and strategic analysis", isCorrect: true },
      { key: "c", text: "Hardware procurement support", isCorrect: false },
      { key: "d", text: "Bug fixing and server maintenance", isCorrect: false },
    ],
  },
  {
    id: "q-mock-04",
    domain: "Foundations",
    moduleNumber: "01",
    prompt: "Which stage of the Business Analysis Process Model immediately follows 'Investigate Situation'?",
    explanation: "After investigating the situation, the analyst proceeds to 'Consider Perspectives' to understand stakeholder views and conflicts.",
    syllabusReference: "BCS BA Foundation Section 1.4: Business Analysis Process Model",
    options: [
      { key: "a", text: "Consider perspectives", isCorrect: true },
      { key: "b", text: "Deploy software", isCorrect: false },
      { key: "c", text: "Close project", isCorrect: false },
      { key: "d", text: "Sign contracts", isCorrect: false },
    ],
  },
  {
    id: "q-mock-05",
    domain: "Foundations",
    moduleNumber: "01",
    prompt: "Which model emphasizes looking at People, Organization, Process, and Information / Technology holistically?",
    explanation: "The POPIT model provides a four-view framework ensuring non-technical dimensions are analyzed thoroughly.",
    syllabusReference: "BCS BA Foundation Section 1.5: Holistic Systems & POPIT",
    options: [
      { key: "a", text: "POPIT model", isCorrect: true },
      { key: "b", text: "Waterfall model", isCorrect: false },
      { key: "c", text: "Porter's 5 Forces", isCorrect: false },
      { key: "d", text: "Ansoff Matrix", isCorrect: false },
    ],
  },
  {
    id: "q-mock-06",
    domain: "Foundations",
    moduleNumber: "01",
    prompt: "What is the key benefit of an agile approach to business analysis?",
    explanation: "Agile BA focuses on iterative collaboration, incremental delivery of business value, and fast feedback loops.",
    syllabusReference: "BCS BA Foundation Section 1.6: Agile Business Analysis",
    options: [
      { key: "a", text: "Eliminating the need for any documentation or stakeholder communication", isCorrect: false },
      { key: "b", text: "Delivering business value incrementally with continuous feedback", isCorrect: true },
      { key: "c", text: "Guaranteeing that no requirements change during development", isCorrect: false },
      { key: "d", text: "Removing all project management oversight", isCorrect: false },
    ],
  },

  // --- Section 2: Strategy Analysis (6 Qs) ---
  {
    id: "q-mock-07",
    domain: "Strategy Analysis",
    moduleNumber: "02",
    prompt: "Which framework is used to analyze macroeconomic external drivers influencing an organization?",
    explanation: "PESTLE scans Political, Economic, Socio-cultural, Technological, Legal, and Environmental factors.",
    syllabusReference: "BCS BA Foundation Section 2.1: External Analysis",
    options: [
      { key: "a", text: "PESTLE analysis", isCorrect: true },
      { key: "b", text: "Resource Audit", isCorrect: false },
      { key: "c", text: "RACI Matrix", isCorrect: false },
      { key: "d", text: "BAM Diagram", isCorrect: false },
    ],
  },
  {
    id: "q-mock-08",
    domain: "Strategy Analysis",
    moduleNumber: "02",
    prompt: "In Porter's Five Forces model, what does 'Buyer Power' refer to?",
    explanation: "Buyer power represents the ability of customers to drive down prices, demand higher quality, or switch easily.",
    syllabusReference: "BCS BA Foundation Section 2.2: Industry Analysis",
    options: [
      { key: "a", text: "The power of procurement managers inside the firm", isCorrect: false },
      { key: "b", text: "The influence customers have on pricing, terms and market demand", isCorrect: true },
      { key: "c", text: "The financial backing of angel investors", isCorrect: false },
      { key: "d", text: "The authority of the project sponsor", isCorrect: false },
    ],
  },
  {
    id: "q-mock-09",
    domain: "Strategy Analysis",
    moduleNumber: "02",
    prompt: "What does the VRIO framework assess regarding organizational capability?",
    explanation: "VRIO evaluates whether internal resources are Valuable, Rare, Inimitable, and Organized to capture value.",
    syllabusReference: "BCS BA Foundation Section 2.3: Internal Capability Analysis",
    options: [
      { key: "a", text: "Value, Rarity, Inimitability, and Organization", isCorrect: true },
      { key: "b", text: "Vision, Risk, Impact, and Outcome", isCorrect: false },
      { key: "c", text: "Velocity, Requirements, Iteration, and Operations", isCorrect: false },
      { key: "d", text: "Validity, Reliability, Integration, and Ownership", isCorrect: false },
    ],
  },
  {
    id: "q-mock-10",
    domain: "Strategy Analysis",
    moduleNumber: "02",
    prompt: "How does a TOWS matrix extend a standard SWOT analysis?",
    explanation: "TOWS directly combines internal strengths/weaknesses with external opportunities/threats to generate actionable strategies (SO, ST, WO, WT).",
    syllabusReference: "BCS BA Foundation Section 2.4: Strategic Synthesis",
    options: [
      { key: "a", text: "By matching internal strengths/weaknesses with external opportunities/threats to create actionable strategic options", isCorrect: true },
      { key: "b", text: "By eliminating the need to examine weaknesses", isCorrect: false },
      { key: "c", text: "By measuring employee timesheet productivity", isCorrect: false },
      { key: "d", text: "By converting qualitative requirements into software code", isCorrect: false },
    ],
  },
  {
    id: "q-mock-11",
    domain: "Strategy Analysis",
    moduleNumber: "02",
    prompt: "Which Balanced Scorecard perspective focuses on staff training, innovation, and corporate culture?",
    explanation: "The Learning and Growth perspective measures organizational capability, human capital, and technology enablement.",
    syllabusReference: "BCS BA Foundation Section 2.5: Balanced Scorecard",
    options: [
      { key: "a", text: "Financial perspective", isCorrect: false },
      { key: "b", text: "Customer perspective", isCorrect: false },
      { key: "c", text: "Internal business process perspective", isCorrect: false },
      { key: "d", text: "Learning and growth perspective", isCorrect: true },
    ],
  },
  {
    id: "q-mock-12",
    domain: "Strategy Analysis",
    moduleNumber: "02",
    prompt: "What is a Critical Success Factor (CSF)?",
    explanation: "CSFs are vital areas of performance where things must go right for an organization to achieve its strategic objectives.",
    syllabusReference: "BCS BA Foundation Section 2.6: Performance Measurement",
    options: [
      { key: "a", text: "A key area in which high performance is necessary for strategic success", isCorrect: true },
      { key: "b", text: "A software bug that crashes the production server", isCorrect: false },
      { key: "c", text: "The date on which a contract expires", isCorrect: false },
      { key: "d", text: "The hourly billing rate of external contractors", isCorrect: false },
    ],
  },

  // --- Section 3: Stakeholder Analysis (7 Qs) ---
  {
    id: "q-mock-13",
    domain: "Stakeholder Analysis",
    moduleNumber: "03",
    prompt: "What is the primary purpose of a stakeholder power-interest grid?",
    explanation: "The grid helps determine appropriate engagement, management, and communication strategies for different stakeholder groups.",
    syllabusReference: "BCS BA Foundation Section 3.1: Stakeholder Categorization",
    options: [
      { key: "a", text: "To determine an appropriate stakeholder engagement and communication approach", isCorrect: true },
      { key: "b", text: "To eliminate difficult stakeholders from project communication", isCorrect: false },
      { key: "c", text: "To rank stakeholders strictly by salary level", isCorrect: false },
      { key: "d", text: "To replace discovery interviews with email surveys", isCorrect: false },
    ],
  },
  {
    id: "q-mock-14",
    domain: "Stakeholder Analysis",
    moduleNumber: "03",
    prompt: "How should stakeholders in the 'High Power, High Interest' quadrant be managed?",
    explanation: "High power, high interest stakeholders are 'Key Players' who must be managed closely through collaborative partnership.",
    syllabusReference: "BCS BA Foundation Section 3.2: Stakeholder Management Matrix",
    options: [
      { key: "a", text: "Manage closely with active partnership and regular collaboration", isCorrect: true },
      { key: "b", text: "Keep informed with quarterly email blasts only", isCorrect: false },
      { key: "c", text: "Provide minimal effort", isCorrect: false },
      { key: "d", text: "Exclude them from scope discussions", isCorrect: false },
    ],
  },
  {
    id: "q-mock-15",
    domain: "Stakeholder Analysis",
    moduleNumber: "03",
    prompt: "What does the letter 'A' stand for in a RACI matrix?",
    explanation: "Accountable is the single individual who has ultimate decision authority and ownership for deliverable sign-off.",
    syllabusReference: "BCS BA Foundation Section 3.3: Responsibilities & RACI",
    options: [
      { key: "a", text: "Assistant", isCorrect: false },
      { key: "b", text: "Accountable (the single person ultimately answerable for the task)", isCorrect: true },
      { key: "c", text: "Auditor", isCorrect: false },
      { key: "d", text: "Author", isCorrect: false },
    ],
  },
  {
    id: "q-mock-16",
    domain: "Stakeholder Analysis",
    moduleNumber: "03",
    prompt: "In stakeholder analysis, what does a 'Champion' attitude describe?",
    explanation: "A champion actively promotes, advocates for, and supports the proposed business change.",
    syllabusReference: "BCS BA Foundation Section 3.4: Stakeholder Attitudes",
    options: [
      { key: "a", text: "A stakeholder who actively supports and advocates for the change initiative", isCorrect: true },
      { key: "b", text: "A stakeholder who secretly opposes the change", isCorrect: false },
      { key: "c", text: "An external regulator with statutory inspection rights", isCorrect: false },
      { key: "d", text: "A neutral observer who takes no part in project discussions", isCorrect: false },
    ],
  },
  {
    id: "q-mock-17",
    domain: "Stakeholder Analysis",
    moduleNumber: "03",
    prompt: "Which elicitation technique is most suitable for understanding tacit, intuitive user actions that users struggle to verbalize?",
    explanation: "Observation (shadowing or protocol analysis) allows the analyst to see real behavior, workarounds, and tacit habits directly.",
    syllabusReference: "BCS BA Foundation Section 3.5: Elicitation Techniques",
    options: [
      { key: "a", text: "Observation / Shadowing", isCorrect: true },
      { key: "b", text: "Written survey", isCorrect: false },
      { key: "c", text: "Reading corporate annual reports", isCorrect: false },
      { key: "d", text: "Sending mass questionnaires", isCorrect: false },
    ],
  },
  {
    id: "q-mock-18",
    domain: "Stakeholder Analysis",
    moduleNumber: "03",
    prompt: "What is a key risk of using open-ended surveys for requirements elicitation?",
    explanation: "Surveys can yield low response rates, ambiguous answers, and lack the ability to ask immediate clarifying follow-up questions.",
    syllabusReference: "BCS BA Foundation Section 3.6: Elicitation Trade-offs",
    options: [
      { key: "a", text: "Inability to clarify ambiguous responses in real time", isCorrect: true },
      { key: "b", text: "They take too much analyst time during distribution", isCorrect: false },
      { key: "c", text: "They cannot be stored electronically", isCorrect: false },
      { key: "d", text: "They violate GDPR in all circumstances", isCorrect: false },
    ],
  },
  {
    id: "q-mock-19",
    domain: "Stakeholder Analysis",
    moduleNumber: "03",
    prompt: "Which stakeholder role represents the business executive who commits funds and takes commercial accountability for the project?",
    explanation: "The Project Sponsor funds the project and holds ultimate commercial ownership for the business benefits.",
    syllabusReference: "BCS BA Foundation Section 3.7: Project Roles",
    options: [
      { key: "a", text: "Project Sponsor", isCorrect: true },
      { key: "b", text: "Lead Developer", isCorrect: false },
      { key: "c", text: "End User Representative", isCorrect: false },
      { key: "d", text: "External Vendor Salesperson", isCorrect: false },
    ],
  },

  // --- Section 4: Business Systems Modelling (7 Qs) ---
  {
    id: "q-mock-20",
    domain: "Systems Modelling",
    moduleNumber: "04",
    prompt: "In a Business Activity Model (BAM), which category includes activities that set targets and measure performance against plan?",
    explanation: "Monitoring and Control activities track performance against plan and initiate corrective action.",
    syllabusReference: "BCS BA Foundation Section 4.1: Business Activity Models",
    options: [
      { key: "a", text: "Monitoring and control activities", isCorrect: true },
      { key: "b", text: "Primary core doing activities", isCorrect: false },
      { key: "c", text: "Enabling activities", isCorrect: false },
      { key: "d", text: "External market events", isCorrect: false },
    ],
  },
  {
    id: "q-mock-21",
    domain: "Systems Modelling",
    moduleNumber: "04",
    prompt: "What do swimlanes represent on a business process model?",
    explanation: "Swimlanes represent organizational roles, departments, or actors responsible for executing specific tasks.",
    syllabusReference: "BCS BA Foundation Section 4.2: Process Modelling",
    options: [
      { key: "a", text: "The roles, departments, or actors responsible for executing activities", isCorrect: true },
      { key: "b", text: "The physical dimensions of office furniture", isCorrect: false },
      { key: "c", text: "The network bandwidth between server racks", isCorrect: false },
      { key: "d", text: "The financial cost of each software module", isCorrect: false },
    ],
  },
  {
    id: "q-mock-22",
    domain: "Systems Modelling",
    moduleNumber: "04",
    prompt: "In process modelling, what is an 'As-Is' process map used for?",
    explanation: "An As-Is process map documents the current operational reality to identify friction, waste, delays, and root causes.",
    syllabusReference: "BCS BA Foundation Section 4.3: Process Improvement",
    options: [
      { key: "a", text: "To document the current process reality and identify inefficiencies", isCorrect: true },
      { key: "b", text: "To design the future software architecture", isCorrect: false },
      { key: "c", text: "To calculate tax returns for corporate accounting", isCorrect: false },
      { key: "d", text: "To describe the company's 10-year marketing strategy", isCorrect: false },
    ],
  },
  {
    id: "q-mock-23",
    domain: "Systems Modelling",
    moduleNumber: "04",
    prompt: "What is an event that initiates a business process called?",
    explanation: "A business event (or trigger) starts the execution of a business process.",
    syllabusReference: "BCS BA Foundation Section 4.4: Business Events",
    options: [
      { key: "a", text: "Trigger / Business event", isCorrect: true },
      { key: "b", text: "Termination node", isCorrect: false },
      { key: "c", text: "Data repository", isCorrect: false },
      { key: "d", text: "Software glitch", isCorrect: false },
    ],
  },
  {
    id: "q-mock-24",
    domain: "Systems Modelling",
    moduleNumber: "04",
    prompt: "Which process redesign tactic involves performing tasks concurrently rather than sequentially?",
    explanation: "Parallel processing executes independent tasks simultaneously to compress lead times and cycle time.",
    syllabusReference: "BCS BA Foundation Section 4.5: Process Redesign Patterns",
    options: [
      { key: "a", text: "Parallel processing / Concurrency", isCorrect: true },
      { key: "b", text: "Sequential queuing", isCorrect: false },
      { key: "c", text: "Outsourcing everything", isCorrect: false },
      { key: "d", text: "Removing all validation checks", isCorrect: false },
    ],
  },
  {
    id: "q-mock-25",
    domain: "Systems Modelling",
    moduleNumber: "04",
    prompt: "What does an entity relationship diagram (ERD) primarily model?",
    explanation: "An ERD models system data entities, their attributes, and the cardinal relationships between them.",
    syllabusReference: "BCS BA Foundation Section 4.6: Data Modelling",
    options: [
      { key: "a", text: "Data entities, attributes, and relationships", isCorrect: true },
      { key: "b", text: "Staff salaries and HR performance reviews", isCorrect: false },
      { key: "c", text: "Server cooling system plumbing", isCorrect: false },
      { key: "d", text: "Customer phone call transcripts", isCorrect: false },
    ],
  },
  {
    id: "q-mock-26",
    domain: "Systems Modelling",
    moduleNumber: "04",
    prompt: "In Use Case Modelling, what represents an external party or system interacting with the solution?",
    explanation: "An Actor represents a role played by an external user, department, or external system interacting with use cases.",
    syllabusReference: "BCS BA Foundation Section 4.7: Use Case Modelling",
    options: [
      { key: "a", text: "Actor", isCorrect: true },
      { key: "b", text: "Scenario", isCorrect: false },
      { key: "c", text: "Boundary box", isCorrect: false },
      { key: "d", text: "Database index", isCorrect: false },
    ],
  },

  // --- Section 5: Requirements Engineering (8 Qs) ---
  {
    id: "q-mock-27",
    domain: "Requirements Engineering",
    moduleNumber: "05",
    prompt: "Which requirement type specifies quality characteristics such as performance, security, and availability?",
    explanation: "Non-functional requirements define the quality attributes and constraints of how the solution performs.",
    syllabusReference: "BCS BA Foundation Section 5.1: Types of Requirements",
    options: [
      { key: "a", text: "Non-functional requirement", isCorrect: true },
      { key: "b", text: "Functional requirement", isCorrect: false },
      { key: "c", text: "Business strategy goal", isCorrect: false },
      { key: "d", text: "User story title", isCorrect: false },
    ],
  },
  {
    id: "q-mock-28",
    domain: "Requirements Engineering",
    moduleNumber: "05",
    prompt: "What is the standard structure of an Agile User Story?",
    explanation: "As a [role], I want [capability], so that [business benefit].",
    syllabusReference: "BCS BA Foundation Section 5.2: User Story Format",
    options: [
      { key: "a", text: "As a [role], I want [feature/action], so that [business outcome/benefit]", isCorrect: true },
      { key: "b", text: "If [condition], then [code execution], else [error]", isCorrect: false },
      { key: "c", text: "The developer shall write code to satisfy the manager", isCorrect: false },
      { key: "d", text: "Given [price], when [purchased], then [deliver receipt]", isCorrect: false },
    ],
  },
  {
    id: "q-mock-29",
    domain: "Requirements Engineering",
    moduleNumber: "05",
    prompt: "In MoSCoW prioritization, what does 'M' (Must Have) signify?",
    explanation: "Must Have requirements are critical, mandatory deliverables without which the solution is legally, operationally, or commercially unviable.",
    syllabusReference: "BCS BA Foundation Section 5.3: MoSCoW Prioritization",
    options: [
      { key: "a", text: "Mandatory requirement essential for launch / viable delivery", isCorrect: true },
      { key: "b", text: "Nice-to-have feature if time permits", isCorrect: false },
      { key: "c", text: "Feature that is explicitly excluded from scope", isCorrect: false },
      { key: "d", text: "A requirement requested by Marketing only", isCorrect: false },
    ],
  },
  {
    id: "q-mock-30",
    domain: "Requirements Engineering",
    moduleNumber: "05",
    prompt: "What does horizontal requirements traceability demonstrate?",
    explanation: "Horizontal traceability tracks a requirement from origin/source forward through design, test cases, and delivery verification.",
    syllabusReference: "BCS BA Foundation Section 5.4: Requirements Traceability",
    options: [
      { key: "a", text: "The path of a requirement from initial business need forward to test cases and solution components", isCorrect: true },
      { key: "b", text: "The reporting line between developers and project managers", isCorrect: false },
      { key: "c", text: "The hierarchy between strategic goals and departmental budgets", isCorrect: false },
      { key: "d", text: "The geographical distance between team members", isCorrect: false },
    ],
  },
  {
    id: "q-mock-31",
    domain: "Requirements Engineering",
    moduleNumber: "05",
    prompt: "Why should requirements avoid including solution design specifics?",
    explanation: "Requirements must define 'WHAT' is needed and 'WHY', leaving 'HOW' to technical solution architects and engineers.",
    syllabusReference: "BCS BA Foundation Section 5.5: Requirements Quality",
    options: [
      { key: "a", text: "To focus on genuine business needs and avoid prematurely constraining solution architecture", isCorrect: true },
      { key: "b", text: "Because developers do not like reading requirements", isCorrect: false },
      { key: "c", text: "Because solution design cannot be tested", isCorrect: false },
      { key: "d", text: "To save ink when printing documentation", isCorrect: false },
    ],
  },
  {
    id: "q-mock-32",
    domain: "Requirements Engineering",
    moduleNumber: "05",
    prompt: "What does the INVEST mnemonic assess in requirements engineering?",
    explanation: "INVEST checks that user stories are Independent, Negotiable, Valuable, Estimable, Small, and Testable.",
    syllabusReference: "BCS BA Foundation Section 5.6: Story Quality & INVEST",
    options: [
      { key: "a", text: "Independent, Negotiable, Valuable, Estimable, Small, Testable", isCorrect: true },
      { key: "b", text: "Integrated, Networked, Verified, Evaluated, Structured, Timed", isCorrect: false },
      { key: "c", text: "Investment, Net Profit, Value, Expense, Strategy, Timeline", isCorrect: false },
      { key: "d", text: "Initiate, Navigate, Verify, Execute, Standardize, Terminate", isCorrect: false },
    ],
  },
  {
    id: "q-mock-33",
    domain: "Requirements Engineering",
    moduleNumber: "05",
    prompt: "In Given-When-Then acceptance criteria, what does 'Given' specify?",
    explanation: "'Given' specifies the initial pre-condition or context before the user takes an action.",
    syllabusReference: "BCS BA Foundation Section 5.7: Acceptance Criteria",
    options: [
      { key: "a", text: "The initial precondition or system state", isCorrect: true },
      { key: "b", text: "The specific user action or event", isCorrect: false },
      { key: "c", text: "The expected observable outcome", isCorrect: false },
      { key: "d", text: "The name of the database table", isCorrect: false },
    ],
  },
  {
    id: "q-mock-34",
    domain: "Requirements Engineering",
    moduleNumber: "05",
    prompt: "What is a primary benefit of using a formal Requirements Catalogue?",
    explanation: "A Requirements Catalogue centralizes requirements metadata, source, owner, priority, status, and verification criteria.",
    syllabusReference: "BCS BA Foundation Section 5.8: Requirements Management",
    options: [
      { key: "a", text: "Centralizing requirement definitions, ownership, acceptance criteria, and status in one controlled repository", isCorrect: true },
      { key: "b", text: "Automatically generating low-level software code", isCorrect: false },
      { key: "c", text: "Replacing the need for developer code reviews", isCorrect: false },
      { key: "d", text: "Allowing every employee to edit requirements without change control", isCorrect: false },
    ],
  },

  // --- Section 6: Business Cases (6 Qs) ---
  {
    id: "q-mock-35",
    domain: "Business Cases",
    moduleNumber: "06",
    prompt: "What is always the baseline option evaluated in any formal Business Case Options Appraisal?",
    explanation: "The 'Do Nothing' (Business as Usual) option provides the benchmark to measure incremental costs and benefits against.",
    syllabusReference: "BCS BA Foundation Section 6.1: Options Appraisal",
    options: [
      { key: "a", text: "Do nothing (Business as Usual)", isCorrect: true },
      { key: "b", text: "Buy the most expensive commercial SaaS tool", isCorrect: false },
      { key: "c", text: "Outsource all staff immediately", isCorrect: false },
      { key: "d", text: "Re-brand the company logo", isCorrect: false },
    ],
  },
  {
    id: "q-mock-36",
    domain: "Business Cases",
    moduleNumber: "06",
    prompt: "Which of the following represents an intangible business benefit?",
    explanation: "Enhanced brand reputation, morale, and customer goodwill are intangible benefits because they cannot be directly measured in immediate cash figures.",
    syllabusReference: "BCS BA Foundation Section 6.2: Tangible vs Intangible Benefits",
    options: [
      { key: "a", text: "Enhanced brand trust, improved staff morale, and stronger customer goodwill", isCorrect: true },
      { key: "b", text: "A £50,000 direct annual saving on software hosting fees", isCorrect: false },
      { key: "c", text: "A 20% reduction in paper invoice printing costs", isCorrect: false },
      { key: "d", text: "A headcount reduction saving £120,000 per year", isCorrect: false },
    ],
  },
  {
    id: "q-mock-37",
    domain: "Business Cases",
    moduleNumber: "06",
    prompt: "What does the 'Payback Period' metric calculate?",
    explanation: "Payback Period measures the exact time it takes for cumulative net cash inflows to equal the initial capital investment outlay.",
    syllabusReference: "BCS BA Foundation Section 6.3: Financial Investment Appraisal",
    options: [
      { key: "a", text: "The time required for cumulative project benefits to equal the initial investment cost", isCorrect: true },
      { key: "b", text: "The total length of the developer sprint cycle", isCorrect: false },
      { key: "c", text: "The notice period required when terminating an employee contract", isCorrect: false },
      { key: "d", text: "The number of hours spent in discovery workshops", isCorrect: false },
    ],
  },
  {
    id: "q-mock-38",
    domain: "Business Cases",
    moduleNumber: "06",
    prompt: "Why is Net Present Value (NPV) preferred over simple payback for long-term investments?",
    explanation: "NPV accounts for the time value of money by discounting future cash flows back to present value using a discount rate.",
    syllabusReference: "BCS BA Foundation Section 6.4: Discounted Cash Flow & NPV",
    options: [
      { key: "a", text: "It recognizes the time value of money by discounting future cash flows", isCorrect: true },
      { key: "b", text: "It does not require any mathematical calculation", isCorrect: false },
      { key: "c", text: "It guarantees that all project risks will be eliminated", isCorrect: false },
      { key: "d", text: "It ignores inflation and capital interest rates", isCorrect: false },
    ],
  },
  {
    id: "q-mock-39",
    domain: "Business Cases",
    moduleNumber: "06",
    prompt: "In risk management, what two core dimensions are evaluated for every identified risk?",
    explanation: "Risk severity is assessed by multiplying Likelihood (Probability) by Impact (Consequence).",
    syllabusReference: "BCS BA Foundation Section 6.5: Risk Assessment",
    options: [
      { key: "a", text: "Likelihood (Probability) and Impact (Consequence)", isCorrect: true },
      { key: "b", text: "Developer age and programming language version", isCorrect: false },
      { key: "c", text: "Document word count and font size", isCorrect: false },
      { key: "d", text: "Office rent and electricity bill", isCorrect: false },
    ],
  },
  {
    id: "q-mock-40",
    domain: "Business Cases",
    moduleNumber: "06",
    prompt: "What is the purpose of a Benefits Realization Review after project implementation?",
    explanation: "A benefits review assesses whether the expected business benefits and ROI stated in the original business case were actually achieved.",
    syllabusReference: "BCS BA Foundation Section 6.6: Benefits Realization",
    options: [
      { key: "a", text: "To verify whether the expected business benefits and ROI in the business case were actually realized in operation", isCorrect: true },
      { key: "b", text: "To blame developers for initial project scope changes", isCorrect: false },
      { key: "c", text: "To delete all project requirements and documentation", isCorrect: false },
      { key: "d", text: "To approve the invoice for the launch party venue", isCorrect: false },
    ],
  },
]
