import type { TranscriptLine } from "@/components/shared/types"
import type { MeetingMinutes, ActionItem } from "./types"

export function generateMeetingMinutes(
  transcript: TranscriptLine[],
  projectName = "Enquiry-to-delivery process transformation",
  projectCode = "ADV-BA-001",
  learnerName = "Amanda Okafor"
): MeetingMinutes {
  const dateStr = new Date().toISOString().split("T")[0]

  // Identify distinct speakers
  const distinctSpeakers = Array.from(
    new Set(transcript.map(t => `${t.speaker} (${t.role})`))
  )
  if (!distinctSpeakers.some(s => s.includes(learnerName))) {
    distinctSpeakers.push(`${learnerName} (Business Analyst)`)
  }

  // Synthesize key discussion points
  const keyDiscussionPoints = [
    "Investigation of enquiry qualification intake and hand-off delay bottlenecks.",
    "Elimination of manual spreadsheet data re-entry causing 4.8-day response lags [ADV-SOP-002].",
    "Scope boundaries: billing engines excluded; focus restricted to intake, CRM qualification, and mobilization.",
    "BCS professional standards requirements: horizontal traceability from problem statements to user stories [BCS-BA-001].",
  ]

  // Synthesize agreed decisions
  const decisionsAgreed = [
    "Confirmed project objective: compress enquiry-to-delivery cycle time from 14 business days to 4 business days.",
    "Agreed that Sarah Mitchell (Project Sponsor) retains commercial sign-off on Project Charter and Business Case.",
    "Agreed that Marcus Cole (BA Supervisor) reviews As-Is and To-Be process swimlanes prior to requirements sign-off.",
    "Agreed that all deliverables must be independently audited by Helen Grant before stage gate completion.",
  ]

  // Action items
  const actionItems: ActionItem[] = [
    {
      id: "act-1",
      task: "Finalise As-Is Enquiry-to-Delivery Process Swimlane Map",
      owner: learnerName,
      dueDate: "Friday, 17:00",
      status: "pending",
    },
    {
      id: "act-2",
      task: "Review discovery notes with Operations Lead to validate hand-off exceptions",
      owner: "Priya Shah & " + learnerName,
      dueDate: "Next Tuesday, 11:00",
      status: "pending",
    },
    {
      id: "act-3",
      task: "Submit Stage 3 deliverable for BA Supervisory coaching review",
      owner: learnerName,
      dueDate: "Next Thursday, 15:00",
      status: "pending",
    },
  ]

  const risksIdentified = [
    "Risk of scope creep if automated billing integration is requested before core intake process stabilizes.",
    "Data cleanliness risk during migration from legacy qualification spreadsheets into CRM workflows.",
  ]

  const markdown = `# ADVANTCORE ACADEMY — PROJECT MEETING MINUTES
**Project:** ${projectName} (${projectCode})  
**Date:** ${dateStr}  
**Lead Business Analyst:** ${learnerName}  

---

## 1. Meeting Attendees
${distinctSpeakers.map(s => `- ${s}`).join("\n")}

## 2. Executive Summary
The project team convened to align on scope boundaries, investigate current operational friction in lead intake, and agree deliverable ownership for Stage 3 Process Modelling.

## 3. Key Discussion Points
${keyDiscussionPoints.map(p => `- ${p}`).join("\n")}

## 4. Formal Decisions Agreed
${decisionsAgreed.map((d, i) => `${i + 1}. **${d}**`).join("\n")}

## 5. Agreed Action Items & Follow-up Deliverables
| # | Action / Deliverable | Owner | Target Due Date | Status |
| :--- | :--- | :--- | :--- | :--- |
${actionItems.map((a, i) => `| ${i + 1} | ${a.task} | ${a.owner} | ${a.dueDate} | ${a.status.toUpperCase()} |`).join("\n")}

## 6. Identified Risks & Guardrails
${risksIdentified.map(r => `- ${r}`).join("\n")}

---
*Generated by Advantcore Academy Meeting Engine · Grounded in BCS Foundation Professional Standards*`

  return {
    id: `min-${Date.now()}`,
    meetingTitle: "Project Scoping & Discovery Meeting",
    projectCode,
    projectName,
    date: dateStr,
    attendees: distinctSpeakers,
    executiveSummary: "Team alignment on enquiry qualification, process modelling scope, and RACI governance.",
    keyDiscussionPoints,
    decisionsAgreed,
    actionItems,
    risksIdentified,
    markdown,
  }
}
