import type { WeekSchedule } from "./types"

export const full12WeekSchedule: WeekSchedule[] = [
  {
    weekNumber: 1,
    title: "Orientation & Foundations",
    moduleTitle: "Module 01: Business analysis foundations",
    projectStageTitle: "Stage 1: Initiation & Problem Scoping",
    hoursEstimated: 10,
    status: "done",
    events: [
      { id: "ev-w1-1", weekNumber: 1, day: "Mon", time: "09:00", title: "Role of the Business Analyst", detail: "Lesson 1.1 & Core Competencies", type: "lesson", durationMinutes: 45, status: "done" },
      { id: "ev-w1-2", weekNumber: 1, day: "Wed", time: "14:00", title: "Project Initiation Briefing", detail: "Review Sarah Mitchell's Commercial Mandate", type: "meeting", durationMinutes: 30, status: "done" },
      { id: "ev-w1-3", weekNumber: 1, day: "Fri", time: "16:00", title: "Problem Statement Deliverable", detail: "Submit Task 1.1 to BA Supervisor", type: "task", durationMinutes: 60, status: "done" },
    ],
  },
  {
    weekNumber: 2,
    title: "Strategy & Scope Boundaries",
    moduleTitle: "Module 02: Strategy analysis",
    projectStageTitle: "Stage 1: Project Charter Sign-off",
    hoursEstimated: 10,
    status: "done",
    events: [
      { id: "ev-w2-1", weekNumber: 2, day: "Mon", time: "10:00", title: "PESTLE & Porter's 5 Forces", detail: "External Environmental Analysis", type: "lesson", durationMinutes: 50, status: "done" },
      { id: "ev-w2-2", weekNumber: 2, day: "Wed", time: "11:00", title: "Project Charter Formulation", detail: "Task 1.2 Scope Boundaries & Exclusions", type: "task", durationMinutes: 60, status: "done" },
      { id: "ev-w2-3", weekNumber: 2, day: "Fri", time: "15:00", title: "Stage 1 Sponsor Sign-off", detail: "Sarah Mitchell Review Gate", type: "review_gate", isFixedDeadline: true, durationMinutes: 30, status: "done" },
    ],
  },
  {
    weekNumber: 3,
    title: "Stakeholder Power-Interest",
    moduleTitle: "Module 03: Stakeholder analysis",
    projectStageTitle: "Stage 2: Discovery & RACI Mapping",
    hoursEstimated: 12,
    status: "done",
    events: [
      { id: "ev-w3-1", weekNumber: 3, day: "Mon", time: "09:30", title: "Power-Interest Grid & Categorization", detail: "Lesson 3.1 Positioning Key Players", type: "lesson", durationMinutes: 45, status: "done" },
      { id: "ev-w3-2", weekNumber: 3, day: "Tue", time: "14:00", title: "Stakeholder Engagement Matrix", detail: "Task 2.1 RACI Governance Table", type: "task", durationMinutes: 60, status: "done" },
      { id: "ev-w3-3", weekNumber: 3, day: "Thu", time: "15:00", title: "Diagnostic Mock Assessment", detail: "10-Question Foundations Check", type: "mock_exam", durationMinutes: 15, status: "done" },
    ],
  },
  {
    weekNumber: 4,
    title: "Operational Discovery",
    moduleTitle: "Module 03: Stakeholder relationships",
    projectStageTitle: "Stage 2: Operational Interviews",
    hoursEstimated: 10,
    status: "done",
    events: [
      { id: "ev-w4-1", weekNumber: 4, day: "Mon", time: "10:00", title: "Elicitation Techniques (Interviews & Observation)", detail: "Lesson 3.4 Active Listening", type: "lesson", durationMinutes: 40, status: "done" },
      { id: "ev-w4-2", weekNumber: 4, day: "Wed", time: "10:30", title: "Discovery Consultation with Priya Shah", detail: "Live Team Room Interview", type: "meeting", durationMinutes: 45, status: "done" },
      { id: "ev-w4-3", weekNumber: 4, day: "Fri", time: "14:00", title: "Discovery Synthesis Log", detail: "Task 2.2 Pain Point Synthesis", type: "task", durationMinutes: 60, status: "done" },
    ],
  },
  {
    weekNumber: 5,
    title: "As-Is Process Swimlanes",
    moduleTitle: "Module 04: Business systems modelling",
    projectStageTitle: "Stage 3: As-Is Process Modelling",
    hoursEstimated: 12,
    status: "active",
    events: [
      { id: "ev-w5-1", weekNumber: 5, day: "Mon", time: "09:00", title: "POPIT Model & Holistic Systems", detail: "Lesson 4.1 Four-View Analysis", type: "lesson", durationMinutes: 45, status: "done" },
      { id: "ev-w5-2", weekNumber: 5, day: "Wed", time: "11:00", title: "As-Is Swimlane Process Mapping", detail: "Task 3.1 Enquiry Intake & Mobilization Map", type: "task", durationMinutes: 90, status: "in_progress" },
      { id: "ev-w5-3", weekNumber: 5, day: "Fri", time: "15:00", title: "BA Supervisor Coaching Review", detail: "Marcus Cole Deliverable Feedback", type: "meeting", durationMinutes: 30, status: "upcoming" },
    ],
  },
  {
    weekNumber: 6,
    title: "To-Be Process & Mid-Point Mock",
    moduleTitle: "Module 04: Process redesign",
    projectStageTitle: "Stage 3: Target Operating Model",
    hoursEstimated: 12,
    status: "upcoming",
    events: [
      { id: "ev-w6-1", weekNumber: 6, day: "Tue", time: "10:00", title: "To-Be Target State Workflow Design", detail: "Task 3.2 Automated Intake Model", type: "task", durationMinutes: 90, status: "upcoming" },
      { id: "ev-w6-2", weekNumber: 6, day: "Thu", time: "14:00", title: "Full 40-Question Mid-Point Mock Exam", detail: "Timed 60-min BCS Simulator Check", type: "mock_exam", durationMinutes: 60, status: "upcoming" },
      { id: "ev-w6-3", weekNumber: 6, day: "Fri", time: "16:00", title: "Stage 3 Independent Review Gate", detail: "Helen Grant Audit", type: "review_gate", isFixedDeadline: true, durationMinutes: 30, status: "upcoming" },
    ],
  },
  {
    weekNumber: 7,
    title: "Requirements Engineering",
    moduleTitle: "Module 05: Requirements engineering",
    projectStageTitle: "Stage 4: Requirements Catalogue",
    hoursEstimated: 12,
    status: "upcoming",
    events: [
      { id: "ev-w7-1", weekNumber: 7, day: "Mon", time: "09:00", title: "Functional vs Non-Functional Requirements", detail: "Lesson 5.1 Quality Attributes", type: "lesson", durationMinutes: 50, status: "upcoming" },
      { id: "ev-w7-2", weekNumber: 7, day: "Wed", time: "14:00", title: "Requirements Catalogue Formulation", detail: "Task 4.1 12 Functional + 4 NFRs", type: "task", durationMinutes: 90, status: "upcoming" },
    ],
  },
  {
    weekNumber: 8,
    title: "User Stories & MoSCoW",
    moduleTitle: "Module 05: Agile user stories",
    projectStageTitle: "Stage 4: Agile Backlog",
    hoursEstimated: 10,
    status: "upcoming",
    events: [
      { id: "ev-w8-1", weekNumber: 8, day: "Mon", time: "10:00", title: "User Stories & Given-When-Then Acceptance", detail: "Lesson 5.2 Gherkin Format", type: "lesson", durationMinutes: 45, status: "upcoming" },
      { id: "ev-w8-2", weekNumber: 8, day: "Wed", time: "13:00", title: "MoSCoW Prioritized User Story Backlog", detail: "Task 4.2 Sprint Ready Backlog", type: "task", durationMinutes: 90, status: "upcoming" },
    ],
  },
  {
    weekNumber: 9,
    title: "Business Case Options Appraisal",
    moduleTitle: "Module 06: Business cases",
    projectStageTitle: "Stage 5: Options Appraisal",
    hoursEstimated: 12,
    status: "upcoming",
    events: [
      { id: "ev-w9-1", weekNumber: 9, day: "Mon", time: "09:30", title: "Cost-Benefit Analysis & Financial Metrics", detail: "Lesson 6.1 Payback, NPV & DCF", type: "lesson", durationMinutes: 60, status: "upcoming" },
      { id: "ev-w9-2", weekNumber: 9, day: "Thu", time: "14:00", title: "Business Case Options Appraisal Document", detail: "Task 5.1 3 Options + Financial ROI", type: "task", durationMinutes: 120, status: "upcoming" },
    ],
  },
  {
    weekNumber: 10,
    title: "Benefits Realisation & Risk",
    moduleTitle: "Module 06: Benefits & Risks",
    projectStageTitle: "Stage 5: Benefits Plan",
    hoursEstimated: 10,
    status: "upcoming",
    events: [
      { id: "ev-w10-1", weekNumber: 10, day: "Tue", time: "11:00", title: "Benefits Realisation Plan & Risk Matrix", detail: "Lesson 6.2 Tangible vs Intangible", type: "lesson", durationMinutes: 45, status: "upcoming" },
      { id: "ev-w10-2", weekNumber: 10, day: "Fri", time: "15:00", title: "Sponsor Business Case Presentation", detail: "Sarah Mitchell Review", type: "meeting", durationMinutes: 45, status: "upcoming" },
    ],
  },
  {
    weekNumber: 11,
    title: "Final Mock Exam & Readiness Audit",
    moduleTitle: "Certification Practice",
    projectStageTitle: "Portfolio Compilation",
    hoursEstimated: 12,
    status: "upcoming",
    events: [
      { id: "ev-w11-1", weekNumber: 11, day: "Tue", time: "10:00", title: "Final BCS 40-Question Mock Exam", detail: "Target: 90% Academy Mastery", type: "mock_exam", durationMinutes: 60, status: "upcoming" },
      { id: "ev-w11-2", weekNumber: 11, day: "Thu", time: "14:00", title: "Executive Case Study Portfolio Assembly", detail: "Compile 5 Approved Deliverables", type: "task", durationMinutes: 90, status: "upcoming" },
    ],
  },
  {
    weekNumber: 12,
    title: "Independent Review & Completion",
    moduleTitle: "Career Acceleration",
    projectStageTitle: "Final Assessment Sign-off",
    hoursEstimated: 8,
    status: "upcoming",
    events: [
      { id: "ev-w12-1", weekNumber: 12, day: "Wed", time: "14:00", title: "Final Independent Portfolio Audit", detail: "Helen Grant Formal Sign-off", type: "review_gate", isFixedDeadline: true, durationMinutes: 60, status: "upcoming" },
      { id: "ev-w12-2", weekNumber: 12, day: "Fri", time: "16:00", title: "Pathway Graduation & Portfolio Export", detail: "Advantcore Certificate of Completion", type: "task", durationMinutes: 30, status: "upcoming" },
    ],
  },
]
